### ISSUE TITLE
social widget on DW link broken 

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#12]
Right side of https://dmbjjp7n9kgns.cloudfront.net/%E5%8F%91%E6%94%B9%E5%A7%94%E5%86%8D%E5%8F%91%E9%A3%99%E9%AB%98%E9%80%9A%E6%8E%A5%E6%8B%9B/a-18247327 and click the twitter image will link to https://dw5.global.ssl.fastly.net/follow-us/a-15674808 Error 403 - We are sorry, but the requested page is not publicly available.

**Comment by ChinaJoe** [comment]
It is the dw.de site's bug:
 http://www.dw.de/follow-us/a-15674808
