### ISSUE TITLE
issues with beijingspring.com mirrors

### ISSUE THREAD

**Issue by jindouyunco** [greatfire/website-mirror-by-proxy#13]
We're using this to mirror [beijingspring.com](http://beijingspring.com) to Fastly and CloudFront and are seeing some discrepancies between our mirrors and the origin site. In some cases just a few characters incorrectly appear as question marks in diamond signs:
[![screen shot 2015-02-23 at 22 58 22](https://cloud.githubusercontent.com/assets/8960371/6343560/164bb6a4-bbb0-11e4-84df-9981830ce05d.png)](https://bjs.global.ssl.fastly.net/bj2/)

In other cases it's a lot more:
[![screen shot 2015-02-23 at 22 59 54](https://cloud.githubusercontent.com/assets/8960371/6343578/90b5ed10-bbb0-11e4-92f6-cde0687fc7be.png)](https://d2j05jhg6u8rz5.cloudfront.net/bj2/)

In every case, some images aren't loading correctly, and some DOM elements which should be created via `document.write` aren't getting created.

And sometimes after reloading it just stays stuck on this screen:
![screen shot 2015-02-23 at 23 09 32](https://cloud.githubusercontent.com/assets/8960371/6343610/638dd572-bbb1-11e4-9648-1cc54359d68e.png)

The only custom configuration we have in conf-local.inc is
```php
Conf::$default_upstream_base_url = 'http://beijingspring.com';
```

Note that the origin has a redirect set up from / to /bj2/index.htm, so we're publicizing mirror urls like `https://<mirror_domain>/bj2/` since `https://<mirror_domain>/` alone doesn't load anyting (i.e. doesn't redirect to `https://<mirror_domain>/bj2/`. We tried setting `Conf::$default_upstream_base_url` to `'http://beijingspring.com/bj2/'` but that created more problems. If there's some other way we should be configuring this please let us know.

And thanks for the great work on this project!

**Comment by greatfire-martin** [comment]
Thanks for the report.

The reason that the mirrors sometimes have a lot of character encoding problems and sometimes fewer is that it depends on whether the default iframe or the JSONP calls return a response first. There was a bug with the JSONP responses which I just fixed - try the latest version.

The source website seems to have general encoding problems. When I visit beijingspring.com using both Chrome and Firefox, some characters also don't render.

Regarding the document.write this will be addressed in an upcoming version.

Regarding the error in the Chrome console and the (almost) blank screen, have all the mirror URLs been added to the alt_base_urls.txt file? Also update to the latest version, this may already have been fixed.

The default URL path should be configured like this:

<?php

Conf::$default_upstream_base_url = 'http://beijingspring.com';
Conf::$default_upstream_url = '/bj2/index.htm';

?>

**Comment by jindouyunco** [comment]
Thanks for your kind help! I changed my configuration as indicated and can now access the site via `https://<mirror_domain>/` rather than `https://<mirror_domain>/bj2/`, thanks.

I cleared my cache, updated to the latest website-mirror-by-proxy (revision 400fda4d3100231db7802b932d6575892b9b6603), and tested refreshing several mirrors multiple times, and unfortunately looks like I was still able to trigger the encoding bug when the JSONP call wins the race:

![cloudfront mirror](https://cloud.githubusercontent.com/assets/8960371/6394096/cb44c8a8-bd94-11e4-9eb6-bc7192301eea.png)

![fastly mirror](https://cloud.githubusercontent.com/assets/8960371/6394116/dcc11e74-bd94-11e4-9876-d4a4b6a7ad22.png)

Other times it does not trigger the bug (presumably when the default iframe wins the race):

![screen shot 2015-02-26 at 08 49 21](https://cloud.githubusercontent.com/assets/8960371/6394985/ee9c27b4-bd9a-11e4-9da6-7f73ac17b78c.png)

I have not been able to reproduce the blank screen bug, which is great.

Let me know if there's any other info I can provide, or if you want the document.write issue tracked in a separate ticket, and thanks again for all your help.

**Comment by greatfire-martin** [comment]
The core issue is that the source website doesn't specify the charset in a HTTP header but in (multiple) HTML meta tags.

But I do think this issues will be resolved in the upcoming version of WMBP which doesn't use iframes.

**Comment by jindouyunco** [comment]
Cool, thanks @greatfire-martin. I'll watch this ticket to follow progress.
*shaking fist at sites' poor coding practices*
