### ISSUE TITLE
Problem with http.so

### ISSUE THREAD

**Issue by fo0nikens** [greatfire/website-mirror-by-proxy#14]
Hi, since 4 days i tried to install greatfire on amazon instance: 
3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
i run install.sh juste after apt-get update/upgrade, restart apache and in /log/apache2/error.log i've this:
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/http.so' - /usr/lib/php5/20100525/http.so: undefined symbol: php_persistent_handle_abandon in Unknown on line 0
any idea please ? (same problem with Ubuntu)
I added :
extension=raphf.so
extension=propro.so
extension=http.so
in php.ini and:
[Fri Feb 27 14:05:22 2015] [notice] caught SIGTERM, shutting down
PHP Warning:  Module 'http' already loaded in Unknown on line 0
PHP Warning:  Module 'propro' already loaded in Unknown on line 0
PHP Warning:  Module 'raphf' already loaded in Unknown on line 0
[Fri Feb 27 14:05:23 2015] [notice] Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u3 configured -- resuming normal operations

and when i configure vhost Apache and conf-local.inc, blank page and log apache : 
[Fri Feb 27 14:36:11 2015] [error] [client 82.234.211.220] PHP Fatal error:  Class 'http\\Client\\Request' not found in /var/www/public/ProxyHttpRequest.inc on line 4

**Comment by fo0nikens** [comment]
Well seems work on Ubuntu except some bug with Js, i'm working on it :) 
Feedback: With PHP 5.3.3-7 php5enmod is not implemented so *.so not load with your script

**Comment by fo0nikens** [comment]
http://ec2-52-16-84-115.eu-west-1.compute.amazonaws.com/2014-fr/ any tips for this problem ? all js, css are blocked

**Comment by greatfire-martin** [comment]
@fo0nikens Glad that you're using our code!

The install.sh script uses php5enmod to enable the HTTP module. This should automatically add the extensions to the php.ini configuration. If you also manually added them they would be loaded twice which explains the warnings.

Which files do you have in /etc/php5/apache2/conf.d/?

"Class 'http\Client\Request' not found" means that the HTTP extension is not loaded. The install.sh script is made for Ubuntu - I haven't tested it on Debian. Google how to enable the PHP HTTP extension on Debian and you should find out. Please share the instructions so others can learn too.

Interesting about missing php5enmod. If you can modify the install.sh script to work without please contribute! Thanks.
