### ISSUE TITLE
Page reloading automatically every second

### ISSUE THREAD

**Issue by RSF-RWB** [greatfire/website-mirror-by-proxy#15]
We have created a mirror > http://ec2-52-16-13-108.eu-west-1.compute.amazonaws.com
The home page is fine but as soon as we are on an article page, the page keeps reolading automatically.
Example : http://ec2-52-16-13-108.eu-west-1.compute.amazonaws.com/en/news/international/4437-amnesty-internationals-annual-report-slams-chinese-treatment-of-tibet

Is this because of  a frame buster on the mirrored website ?

**Comment by greatfire-martin** [comment]
Indeed, I think it's because of a frame buster:

    if(top.location!=self.location)top.location=self.location;

You can fix it in WMBP by adding something like this to the configuration (not tested):

    TextInternalUrlFilters::addSearch('if(top.location!=self.location)', 'if(0)');

**Comment by RSF-RWB** [comment]
Great ! Problem solved ! Thank you !
