### ISSUE TITLE
double "/" in urls (after domain name)

### ISSUE THREAD

**Issue by RSF-RWB** [greatfire/website-mirror-by-proxy#16]
This mirror automatically include a double // at the beginning of each urls on the homepage
http://ec2-52-16-42-179.eu-west-1.compute.amazonaws.com/
example : https://bahrainmirror.global.ssl.fastly.net//news/22621.html

Have you ever face this kind of issue ?

**Comment by greatfire-martin** [comment]
What's the upstream URL (source website)?

**Comment by RSF-RWB** [comment]
The upstream address : http://bahrainmirror.com/

**Comment by RSF-RWB** [comment]
I think I have a beginning of a clue for this. The website http://bahrainmirror.com/ uses on its pages relatives urls. The problem is that those urls do not start with a "/" and start directly with the name of the repository. Example : <a href="news/22821.html">some text</a>

To solve the problem, I had to remove the test line 60 : 

                            // If path does not start with a slash, prepend current path directory.
                            if ($attr_val_components['path'][0] != '/') {
                                $attr_val_components['path'] = dirname(
                                    $request->getUrlComponent('path')) . '/' .
                                     $attr_val_components['path'];
                            }

Now it works.
