### ISSUE TITLE
镜像增加分享功能 

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#19]
可以把这个添加到banner上，放在Github链接后面。

可以参考https://www.gusouk.com/ 下面的社交分享widget

**Comment by Behemouth** [comment]
这个网站已经打不开了。我们可以考虑用 addthis.com（但是国内无法访问）或jiathis.com（国内山寨版）。

**Comment by Behemouth** [comment]
可惜国内几个都不支持HTTPS。我试了JiaThis、bShare、百度分享，都不支持HTTPS。

我们要用 Addthis.com 的吗？

**Comment by percyalpha** [comment]
Addthis 国内可以访问啊？ https://en.greatfire.org/https/addthis.com
我们可以用这个。谢谢

**Comment by Behemouth** [comment]
先选择了 Jiathis.com 侧边栏分享 ，JS经过了我们的代理。CDT镜象上已经起用。没问题的话就用它吧，Addthis 自定义版需要高级帐户
