### ISSUE TITLE
javascript redirection problem

### ISSUE THREAD

**Issue by RSF-RWB** [greatfire/website-mirror-by-proxy#20]
In am mirroring a website : http://www.mingjingnews.com
The mirror address is  : http://ec2-52-16-4-193.eu-west-1.compute.amazonaws.com/

The mirror page only display this : 

    ��<html> <head> <script>location.href='MIB/index.aspx'</script> </head> </html>

It seems that a js script is automatically redirect to /MIB/
I tried in the conf-local.inc to add 

    TextInternalUrlFilters::addSearch('"/MIB/"');

But I still have the same error. Should I add something else in the filters ?

**Comment by greatfire-martin** [comment]
I don't see that script on the source website, but generally the way to rewrite it would be:

    TextInternalUrlFilters::addSearch("location.href='MIB", "location.href='./MIB");

Since the default URL for the website isn't /, you can probably avoid the redirection altogether by adding:

    Conf::$default_upstream_url = '/MIB/index.aspx';

Hope this helps!

**Comment by RSF-RWB** [comment]
thx, we'll give it a try !
