### ISSUE TITLE
下载不了FREEBROWSER

### ISSUE THREAD

**Issue by luckypoem** [greatfire/website-mirror-by-proxy#21]
HI.
我下载不了FREEBROWSER，下载失败。无论是https://raw.githubusercontent.com/greatfire/z/master/FreeBrowser-1.1.apk还是https://raw.githubusercontent.com/greatfire/z/master/FreeBrowser-1.0.apk都下载失败（我浏览器是翻墙状态的），怎么回事？
可否把FreeBrowser-1.1.apk上传到某个网盘，贴出下载地址供人下载呢？
我找不到其他地方提交问题，只好在此提交，请见谅。

**Comment by ghfdbk** [comment]
@luckypoem，这位已经通过邮箱反馈了，此issue申请关闭

**Comment by percyalpha** [comment]
网盘下载地址

FreeBrowser-1.1.apk 
https://mega.co.nz/#!vs0QAToA!4ZqFmlvaevtWj4NDoFZzy_cqCTtnBYU-sWHcOelFk8Q
