### ISSUE TITLE
Google二级链接短暂时间无法打开

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#22]
![image](https://cloud.githubusercontent.com/assets/7925929/6612858/a52ebc70-c8be-11e4-8f58-6346378241d1.png)

使用环境：
系统：win 7 sp1 ultimate x64
浏览器：Cyberfox最新版本(第三方编译的firefox x64版本，据悉，核心仍为官方的)，更换其它浏览器情况一样。

@ghfdbk 测试时也遇到了这个错误，应该是服务器问题。现在已经恢复

**Comment by ghfdbk** [comment]
Google镜像已经没有了，此问题已失效
