### ISSUE TITLE
自由微博上的Google API

### ISSUE THREAD

**Issue by ghfdbk** [greatfire/website-mirror-by-proxy#24]
有用户希望提供自由微博的Google API

**Comment by greatfire-martin** [comment]
@ghfdbk 什么意思？

**Comment by ghfdbk** [comment]
这是当时用户的反馈：“您好，自由微博上的的google api 全部被屏蔽掉了，您能帮我发一个稳定的google api 吗，谢谢您一直以来的
google 服务“

2015-06-25 10:52 GMT+08:00 greatfire-martin <notifications@github.com>:

**Comment by greatfire-martin** [comment]
是说一个google镜像的地址吗？这样的话可以用github上的google网页。

**Comment by ghfdbk** [comment]
我也没有理解，再次询问了用户，没有回复

2015-06-25 11:15 GMT+08:00 greatfire-martin <notifications@github.com>:
