### ISSUE TITLE
Loading page doesn't show up when DNS poisoned 

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#26]
First access d1s5ussrz0ovn0.cloudfront.net outside of GFW. Then access it inside and click on any article. The loading page is not cached when opening the new article page.

**Comment by Behemouth** [comment]
The original link was broken. Which mirror site of this link?
 But from the description, it seems this is the intended behavior:
> Then access it inside and click on any article

The loading page of an already blocked site only appears if the user had visit the same page before. If it's the first time the user visit this link and the domain was blocked, anything except a network error page will display.

But I'm doubting how could you click an inside article when the domain was poisoned? When the current domain was poisoned, it will auto check available domain and redirect to it.
