### ISSUE TITLE
DW, FW only are still using fastly URLs

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#27]
Please check @ghfdbk 's status sheet

**Comment by requiredfield** [comment]
Just saw this and figured I could jump in and fix it. Switched DW and FW over to the wam rewrite branch, enabled only cloudfront, and set up the @hourly reup cronjob and the @daily rotate. https://github.com/greatfire/wiki#readme picked up the new cloudfront mirrors already.

@greatfire-martin, Using the GreatFire AWS credentials was causing `botocore.exceptions.ClientError: An error occurred (TooManyDistributions) when calling the CreateDistribution operation: Processing your request will cause you to exceed the maximum number of distributions allowed.` I don't have access to the AWS console so it's not easy for me to delete some old distributions to make room. So I temporarily switched AWS credentials to a personal account so it'd let us create some new mirrors. Let me know when there's space freed up on the GreatFire account I'll switch back.

Gotta go offline for a bit but will be back later if anything comes up.

**Comment by greatfire-martin** [comment]
Thanks @requiredfield. We have indeed hit a limit. I will delete old ones ASAP.

**Comment by greatfire-martin** [comment]
@requiredfield Some available now - will delete more

**Comment by greatfire-martin** [comment]
@requiredfield More than 100 available now - good to go

**Comment by requiredfield** [comment]
@greatfire-martin Cool, switched CDT and FW back to GreatFire AWS account.
