### ISSUE TITLE
track mirror accessibility/blocking/redirection on the client-side

### ISSUE THREAD

**Issue by requiredfield** [greatfire/website-mirror-by-proxy#28]
To complement our server-side tracking of mirror blocking, we should also track events like "user loaded mirror A successfully", "user could not load mirror B", "user redirected from mirror C to D" on the client-side. This could be done through Google Analytics' custom event reporting but we could also roll our own.

**Comment by Behemouth** [comment]
@greatfire-martin 
Could we use another analytics service? As this result showed, google analytics is almost inaccessible in China:
http://ce.cloud.360.cn/Snapshot?snapshot=620e31d73e8ab462956372f3be869b13&url=https://ssl.google-analytics.com/ga.js

**Comment by greatfire-martin** [comment]
@Behemouth I don't think that 360 testing is correct. I just tested manually and that GA URL does not seem to be blocked. We are tracking lots of services using GA and I haven't noticed any problems. Our own GF system also reports it as unblocked (https://zh.greatfire.org/https/ssl.google-analytics.com/ga.js).

**Comment by Behemouth** [comment]
This has been implemented in WeedProxite now.

Config.js add: 
```
{
  "gaTrackingID":"UA-XXXX"
}
```

The custom events:
```
    ga('send', 'pageview')  // pageview is enough for current domain load success 

   // load fail
    ga('send', 'event', 'mirror', 'fail',"example.cloudfront.net")

   // redirect domain a to domain b
    ga('send', 'event', 'mirror', 'redirect',"a.cloudfront.net > b.cloudfront.net")
```

So now you need to give me the gaTrackingID, I'll update it in sites config repo.
Ramsey  just do update WeedProxite (on Azure) as usual, then it will work.

**Comment by requiredfield** [comment]
Thanks Joe, just submitted a PR for this: Behemouth/sites#2

Once that's merged, I should do the following for each of our existing mirrors, right?:

1. re-upload config.js
1. re-run `npm install --production git+https://github.com/Behemouth/WeedProxite.git`
1. re-run `./node_modules/.bin/proxite init`

**Comment by Behemouth** [comment]
@requiredfield Yes. I have merged it. 
BTW: I supposed WAM azure.py already have the "Install or Update site" function. Every time it updated, we just need to redo this "update/reinstall" process on each existing Azure server.

**Comment by requiredfield** [comment]
I just tried this for siteid `52gi8` and after uploading the new config.js, the `npm install` command failed with
```
{
    "Error": "\r\nnpm ERR! WeedProxite@0.1.2 postinstall: `node ./bin/postinstall`\r\nnpm ERR! Exit status 2\r\nnpm ERR! \r\nnpm ERR! Failed at the WeedProxite@0.1.2 postinstall script.\r\nnpm ERR! This is most likely a problem with the WeedProxite package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     node ./bin/postinstall\r\nnpm ERR! You can get their info via:\r\nnpm ERR!     npm owner ls WeedProxite\r\nnpm ERR! There is likely additional logging output above.\r\nnpm ERR! System Windows_NT 6.2.9200\r\nnpm ERR! command \"node\" \"D:\\\\Program Files (x86)\\\\npm\\\\1.4.28\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js\" \"install\" \"--production\" \"git+https://github.com/Behemouth/WeedProxite.git\"\r\nnpm ERR! cwd D:\\home\\site\\wwwroot\r\nnpm ERR! node -v v0.10.32\r\nnpm ERR! npm -v 1.4.28\r\nnpm ERR! code ELIFECYCLE\r\n",
    "ExitCode": 1,
    "Output": "\r\n> WeedProxite@0.1.2 postinstall D:\\home\\site\\wwwroot\\node_modules\\WeedProxite\r\n> node ./bin/postinstall\r\n\r\n"
}
```
Bug in weedproxite or something on my end?

**Comment by Behemouth** [comment]
@requiredfield  Fixed. Once agian strange bug only on Azure windows. :sob:

**Comment by requiredfield** [comment]
Thanks for fixing. CDT Azure mirrors have now all been updated. (Still waiting till GFWA includes blocking data to start monitoring and reporting them to Centrice.)
/cc @percyalpha @greatfire-martin
