### ISSUE TITLE
How to handle languages as a path and avoid loop

### ISSUE THREAD

**Issue by dzogrim** [greatfire/website-mirror-by-proxy#29]
Hello.

How is it possible to handle tons of relative links to be hard rewrited ?
This to avoid URL to be added and added to the end… and loop like this.

For example : 
http://thevps.cdn.tld/public/en/
http://thevps.cdn.tld/public/en/en/
http://thevps.cdn.tld/public/en/en/pub
http://thevps.cdn.tld/public/en/en/pub/en/news

Or with the home button : 
http://thevps.cdn.tld/public/en/
http://thevps.cdn.tld/public/en/en/
http://thevps.cdn.tld/public/en/en/en/
http://thevps.cdn.tld/public/en/en/en/en/
http://thevps.cdn.tld/public/en/en/en/en/en/

where relative links are :
en|fr|de| > lang.
/pub
/news

only the home would work.
And then… nothing more.
Added 
```javascript
TextInternalUrlFilters::addSearch("base href='./", "base href='/");
TextInternalUrlFilters::addSearch("href='./en/", "href='./");
TextInternalUrlFilters::addSearch("href='./fr/", "href='./");
```
then it's working… for the first link. Doesn't stop to add and add path at the end… mixing pathes.

:/ sorry… but it's looping 

In some other words is there any way to better handle relative href ?
Thx

**Comment by Behemouth** [comment]
@dzogrim , We have developped a new mirror site proxy(with Node.js): 
https://github.com/Behemouth/WeedProxite

This problem was fixed in the new proxy. Would you like to try it?

**Comment by dzogrim** [comment]
@Behemouth thank you ! I'll give it a try, but at this time, after a quick install, I got errors like:
```javascript
ReferenceError: config is not defined
    at Middleware.use.after (/usr/local/lib/node_modules/WeedProxite/lib/Site.js:294:55)
    at Middleware._after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:222:25)
    at runMiddleware (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:373:25)
    at /usr/local/lib/node_modules/WeedProxite/lib/Server.js:326:18
    at Middleware.after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:163:14)
    at Middleware._after (/usr/local/lib/node_modules/WeedProxite/lib/Middleware.js:222:25)
    at runMiddleware (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:373:25)
    at /usr/local/lib/node_modules/WeedProxite/lib/Server.js:326:18
    at Site.Server._prepareProxyResponse (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:329:14)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/WeedProxite/lib/Server.js:288:24)
```

**Comment by amep-lotus** [comment]
@dzogrim, I also have language site as subdirectory. But i don't know where to make changes in order to work with mirror. 

Our mirror site is https://vt.global.ssl.fastly.net/   and I want https://vt.global.ssl.fastly.net/cn to work. Right now it is redirecting to original website. If you find any way to work around please share.

**Comment by dzogrim** [comment]
@amep-lotus Do you have *every* languages in subdirectories? Anyway you should try this: https://github.com/Behemouth/WeedProxite as @Behemouth advised me… it's working nicely!

**Comment by Behemouth** [comment]
@amep-lotus  Try [WeedProxite](https://github.com/Behemouth/WeedProxite).

Here is an example config, main.js:
```javascript
// main.js
// add below lines
replaceBody = require('WeedProxite/lib/middlewares/replaceBody');
site.use({
  mime:'text/html',
  after:replaceBody(
          ['http://www.vot.org/','/http-colon-//www.vot.org/'],
          ['http:\\/\\/www.vot.org\\/','/http-colon-//www.vot.org/'],
          ['http:\\/\\/vot.org\\/','/http-colon-//vot.org/']
        )
});
//  before 
// site.useDefault();
```

config.js:
```javascript
module.exports = {
  upstream: "http://www.vot.org",
  port:process.env.port || '1989',
  host: process.env.host || '127.0.0.1',
  enableAppcache:true,
  enableShareWidget:true,
  allowHosts:[
    'vot.org',
    'developer.android.com',
    'ajax.googleapis.com',
    'translate.google.com',
    'maxcdn.bootstrapcdn.com',
    'pingback.issuu.com',
    's.ytimg.com',
    'www.google.com',
    'image.issuu.com',
    'apis.google.com',
    'fonts.googleapis.com',
    'platform.twitter.com',
    'v3.jiathis.com',
    'id.jiathis.com'
  ],
  mirrorLinksFile: "./alt_base_urls.txt"
};
```

**Comment by amep-lotus** [comment]
@Behemouth Thank you for your suggestion. I have only one language folder. If i use WeedProxite then i have to setup the mirror site again right?  Is there possible way to work around with website-mirror-by-proxy for one language. If not then i have to try WeedProxite.

**Comment by Behemouth** [comment]
Setup WeedProxite is easy. I have created an example site at
https://github.com/Behemouth/sites/tree/master/vot

You can follow the README to run the site.

**Comment by dzogrim** [comment]
Yes @amep-lotus WeedProxite is really cool and easy to install. Works great! Thx @Behemouth!

**Comment by amep-lotus** [comment]
Thanks @Behemouth for config.js and main.js you had created for our site. I installed WeedProxite as instructed at https://github.com/Behemouth/WeedProxite/blob/master/README.md.  When i run        npm install --production git+https://github.com/Behemouth/WeedProxite.git 

it creates node_modules directory in web root directory and which contain WeedProxite directory. I copied config.js and main.js files you had created for us at https://github.com/Behemouth/sites/tree/master/vot

I created alt_base_urls.txt in WeedProxite directory itself and change path in config.js. Then i run node main.js and i get Site serving on 127.0.0.1:1989...at terminal and when i check the site it is just displaying the default apache page. 

did i do something wrong in setup?  I want to set up mirror with WeedProxite. Help me please.

Thank you

**Comment by Behemouth** [comment]
> when i check the site it is just displaying the default apache page.
Which url do you visit in browser? It should be "http://127.0.0.1:1989/".

You need to config apache as a reverse proxy,see:
https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

for example,edit `sites-enabled/your-site.conf`:

<VirtualHost *:*>
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:1989/
    ProxyPassReverse / http://127.0.0.1:1989/

    ServerName your-domain.com
</VirtualHost>
