### ISSUE TITLE
handling links 

### ISSUE THREAD

**Issue by percyalpha** [greatfire/website-mirror-by-proxy#3]
If the original website has 
`< <a href="javascript:;">xxx</a> >`  the mirror will change it to be `<a href="./;">xxx</a>`

For example, links on https://pt3.global.ssl.fastly.net/

**Comment by Behemouth** [comment]
I can't reproduce it on my local version.  The online mirror site not work: 
https://pt19.global.ssl.fastly.net/
> unknown domain: pt19.global.ssl.fastly.net
I have no access to this mirror server.
