### ISSUE TITLE
New Google mirrors

### ISSUE THREAD

**Issue by greatfire-martin** [greatfire/website-mirror-by-proxy#9]
Eg https://google.global.ssl.fastly.net

**Comment by percyalpha** [comment]
On iPad, the search bottom sometimes doesn't work. (Fastly one)
On iPhone, it shows a tablet view rather than mobile view. Making it very hard to use.

**Comment by greatfire-martin** [comment]
We got some captcha issues again. I fixed a problem with filling them in - now that works at least. Also there seem to be charset conversion problems sometimes. I have supposedly fixed it but let's keep an eye on it.

**Comment by greatfire-martin** [comment]
Charset bug fixed - again

**Comment by percyalpha** [comment]
Urgent bug: Chinese search query will cause random characters!

>

-- 
Percy Alpha(PGP <https://en.greatfire.org/contact#alt>)
GreatFire.org Team

**Comment by greatfire-martin** [comment]
@percyalpha You mean the search keyword itself gets messed up? I can see that problem. Fixing..

**Comment by greatfire-martin** [comment]
Should be fixed now

**Comment by greatfire-martin** [comment]
Also, I think the tablet/phone issue should be solved

**Comment by percyalpha** [comment]
@martin, on mobile, it doesn't show a mobile interface. 
This is a generic problem. Pao-Pao mirror doesn't show pao-pao mobile interface either

**Comment by greatfire-martin** [comment]
Will look into mobile issue.

Other problems solved?

**Comment by percyalpha** [comment]
Yes.

**Comment by greatfire-martin** [comment]
mobile view, fixed on google. Let me know if OK. Not rolled out on other mirrors yet

**Comment by percyalpha** [comment]
The typing is rather hard on mobile view. I remembered you said before it's because how iOS deals with iFrame?

**Comment by greatfire-martin** [comment]
I know that was a problem in the past. I tried it now though and I don't see a problem. Which browser, iOS version are you using, and what is the problem more specifically?

**Comment by percyalpha** [comment]
Looks like it's a Chrome iOS problem. Test on safari iOS, it works.
